apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-eks-anywhere
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: hello-eks-anywhere
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-eks-anywhere
  template:
    metadata:
      labels:
        app: hello-eks-anywhere
    spec:
      containers:
        - name: hello
          image: {{.Values.sourceRegistry}}{{ template "template.image" .Values }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TITLE
              value: {{ .Values.title | quote}}
            - name: SUBTITLE
              value: {{ .Values.subtitle | quote}}
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
