apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-eks-anywhere.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: LoadBalancer
  selector:
    app: hello-eks-anywhere
  ports:
    - port: 80
